version: "3.8"
services:
  web-app:
    image: docspert-web:latest
    container_name: docspert-web-container
    ports:
      - "8000:8000"
    entrypoint: ["/bin/sh", "/app/startup.sh"]
    volumes:
      - .:/app  # Bind volume to reflect changes
