name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t docspert:latest

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v3
    - name: DockerHub Login
      uses: docker/login-action@v3
      with: 
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with: 
        push: true
        tags: dockerspert-github:latest
